# Generated by Django 4.2.13 on 2024-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="Lease_receive",
            field=models.CharField(
                choices=[
                    ("Lease", "Lease"),
                    ("receive", "receive"),
                    ("reserve", "reserve"),
                    ("cancel_reserve", "cancel_reserve"),
                ],
                default="Lease",
                max_length=255,
            ),
        ),
    ]
