# Generated by Django 4.2.13 on 2024-05-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0002_alter_transactions_lease_receive"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelReserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancel_reserve_date",
                    models.DateField(verbose_name="cancel_reserve_date"),
                ),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lease_date", models.DateField(verbose_name="Lease_date")),
                (
                    "must_receive_date",
                    models.DateField(null=True, verbose_name="transaction_date"),
                ),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_date", models.DateField(verbose_name="receive_date")),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name=""
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applibrary.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserve_date", models.DateField(verbose_name="reserve_date")),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name=""
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="initial stock"
            ),
        ),
        migrations.DeleteModel(
            name="Transactions",
        ),
        migrations.AddField(
            model_name="reserve",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.book"
            ),
        ),
        migrations.AddField(
            model_name="reserve",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.userident"
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.book"
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.userident"
            ),
        ),
        migrations.AddField(
            model_name="cancelreserve",
            name="reserve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.reserve"
            ),
        ),
    ]
