# Generated by Django 4.2.13 on 2024-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0004_bookanalyse_alter_author_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookAnalyse",
        ),
    ]
