# Generated by Django 4.2.13 on 2024-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0005_delete_bookanalyse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_published_date",
            field=models.IntegerField(verbose_name="Book Published Date"),
        ),
    ]
