# Generated by Django 4.2.13 on 2024-05-19 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0006_alter_book_book_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userident",
            name="is_staff",
        ),
    ]
