# Generated by Django 4.2.13 on 2024-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0009_alter_lease_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name=""
            ),
        ),
    ]
