# Generated by Django 4.2.13 on 2024-05-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applibrary", "0010_alter_lease_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receive",
            name="lease",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="applibrary.lease"
            ),
        ),
    ]
